[package]
name = "rosu-ur-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osu-db = "0.3.0"
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "expose-mode-objects" }
